apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nginx-statefulset
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
